apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-app.fullname" . }}-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}