version: '3'
services:
  jupyter: 
    container_name: jupyter_container
    image: jupyter/datascience-notebook:b418b67c225b
    volumes:
     - jp_db_film:/home/jovyan/work
    ports:
     - "8888:8888"
  db:
    image: postgres
    container_name: postgres_container
    volumes:
      - pg_db_film:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_film
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5555:4444"
volumes:
  jp_db_film:
    external: true 
  pg_db_film:
    external: true
